/// Flutter icons CategoriesIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CategoriesIcon
///      fonts:
///       - asset: fonts/CategoriesIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CategoriesIcon {
  CategoriesIcon._();

  static const _kFontFam = 'CategoriesIcon';

  static const IconData bar_cafe = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData communication_internet_wifi = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData communication_phone = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData communication_postal_services = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData communication_software = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData electronics_smartphone = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData emoji_smiley = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData energy_bulb = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData financial_expense_advisory = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData financial_expense_charge_fees = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData financial_expense_child_support = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData financial_expense_loan = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData financial_expense_main_money = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData financial_expense_tax = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData gifts = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData groceries = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData health_beauty_cream = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData house = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData income_grant = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData income_interests = IconData(0xe813, fontFamily: _kFontFam);
  static const IconData income_lending = IconData(0xe814, fontFamily: _kFontFam);
  static const IconData income_main_coins = IconData(0xe815, fontFamily: _kFontFam);
  static const IconData income_refund = IconData(0xe816, fontFamily: _kFontFam);
  static const IconData income_rental_income = IconData(0xe817, fontFamily: _kFontFam);
  static const IconData income_sale = IconData(0xe818, fontFamily: _kFontFam);
  static const IconData income_wages = IconData(0xe819, fontFamily: _kFontFam);
  static const IconData investments_collection = IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData investments_financial_investment = IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData investments_main = IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData investments_realty = IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData investments_savings = IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData jewels_diamond = IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData kids = IconData(0xe820, fontFamily: _kFontFam);
  static const IconData life_and_entertainment_alcohol = IconData(0xe821, fontFamily: _kFontFam);
  static const IconData life_and_entertainment_book = IconData(0xe822, fontFamily: _kFontFam);
  static const IconData life_and_entertainment_education = IconData(0xe823, fontFamily: _kFontFam);
  static const IconData life_and_entertainment_fitness = IconData(0xe824, fontFamily: _kFontFam);
  static const IconData life_and_entertainment_healthcare = IconData(0xe825, fontFamily: _kFontFam);
  static const IconData life_and_entertainment_hobbies_heart = IconData(0xe826, fontFamily: _kFontFam);
  static const IconData life_and_entertainment_holiday_trip = IconData(0xe827, fontFamily: _kFontFam);
  static const IconData life_and_entertainment_life_events_birthday_cake = IconData(0xe828, fontFamily: _kFontFam);
  static const IconData life_and_entertainment_lottery = IconData(0xe829, fontFamily: _kFontFam);
  static const IconData life_and_entertainment_main = IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData life_and_entertainment_sports_events = IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData life_and_entertainment_tv_streamingnetflix = IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData life_and_entertainment_wellness_cosmetics = IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData mortgage = IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData pets_pawprint = IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData pharmacy_medicine = IconData(0xe830, fontFamily: _kFontFam);
  static const IconData property_insurance = IconData(0xe831, fontFamily: _kFontFam);
  static const IconData rent = IconData(0xe832, fontFamily: _kFontFam);
  static const IconData repair = IconData(0xe833, fontFamily: _kFontFam);
  static const IconData restaurant = IconData(0xe834, fontFamily: _kFontFam);
  static const IconData services_support_settings = IconData(0xe835, fontFamily: _kFontFam);
  static const IconData stationery = IconData(0xe836, fontFamily: _kFontFam);
  static const IconData transport_airplane = IconData(0xe837, fontFamily: _kFontFam);
  static const IconData transport_bus = IconData(0xe838, fontFamily: _kFontFam);
  static const IconData transport_businessbag = IconData(0xe839, fontFamily: _kFontFam);
  static const IconData transport_car = IconData(0xe83a, fontFamily: _kFontFam);
  static const IconData transport_taxi = IconData(0xe83b, fontFamily: _kFontFam);
  static const IconData tshirt = IconData(0xe83c, fontFamily: _kFontFam);
  static const IconData vehicle_car_insurance = IconData(0xe83d, fontFamily: _kFontFam);
  static const IconData vehicle_car_rental = IconData(0xe83e, fontFamily: _kFontFam);
  static const IconData vehicle_fuel = IconData(0xe83f, fontFamily: _kFontFam);
  static const IconData vehicle_leasing = IconData(0xe840, fontFamily: _kFontFam);
  static const IconData vehicle_maintenance = IconData(0xe841, fontFamily: _kFontFam);
  static const IconData vehicle_parking = IconData(0xe842, fontFamily: _kFontFam);
}
