/// Flutter icons MyIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'MyIcons';

  static const IconData singlecoinicon = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData walleticon = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData dressandaccessoriesicon = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData furnitureicon = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData electronics_icon = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData shopping_list = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData shopping_icon = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData coinsicon = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData fast_foods_icon = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData furnitures_icon = const IconData(0xe809, fontFamily: _kFontFam);
}
